spring:
  application:
    name: catalog-service

server:
  port: 9010

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://registry-service:8761/eureka}
    fetch-registry: true
kafka:
  topic: stat
  user: vzl94vf1
  pswd: VgOZuGldD16LICAuljOaaoOX9XqqKcNL
  servers: "velomobile-01.srvs.cloudkafka.com:9094,velomobile-02.srvs.cloudkafka.com:9094,velomobile-03.srvs.cloudkafka.com:9094"

