spring:
  application:
    name: catalog-service

server:
  port: 9010

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://registry-service:8761/eureka}
    fetch-registry: true
