spring:
  application:
    name: productapi-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0
  data:
    cassandra:
      keyspace-name: product_statistics
      contact-points: cassandra
      schema-action: create_if_not_exists


server:
  port: 9030

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://registry-service:8761/eureka}
    fetch-registry: true

