spring:
  application:
    name: productapi-service
  sleuth:
    sampler:
      probability: 1.0
  data:
    cassandra:
      keyspace-name: product_statistics
      contact-points: cassandra
      schema-action: create_if_not_exists


server:
  port: 9030

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://registry-service:8761/eureka}
    fetch-registry: true

kafka:
  group: cassandra
  topic: stat
  user: vzl94vf1
  pswd: VgOZuGldD16LICAuljOaaoOX9XqqKcNL
  servers: "velomobile-01.srvs.cloudkafka.com:9094,velomobile-02.srvs.cloudkafka.com:9094,velomobile-03.srvs.cloudkafka.com:9094"

