version: '3'
services:
  registry-service:
    image: registry-service
    container_name: registry-service
    build: ./registry
    ports:
      - "8761:8761"
      - "8787:8787"
    networks:
      - emp-network

  inventory-service:
    image: inventory-service
    container_name: inventory-service
    build: ./inventory
    ports:
      - "9020:9020"
      - "8786:8787"
    networks:
      - emp-network
    links:
      - registry-service:registry-service
    depends_on:
      - registry-service

  product-service:
    image: productapi
    container_name: product-service
    build: ./productapi
    ports:
      - "9030:9030"
      - "8785:8787"
    networks:
      - emp-network
    links:
      - registry-service:registry-service
    depends_on:
      - registry-service

networks:
  emp-network:
    driver: bridge