spring:
  application:
    name: inventory-service

server:
  port: 9020

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

