FROM abrtech/alpine-oraclejdk8
ADD ["target/catalog-service-0.0.1-SNAPSHOT.jar", "app.jar"]
EXPOSE 9010 8787
ENV JAVA_OPTS="-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n"
RUN sh -c 'touch /app.jar'
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
